// src/components/Floor/Trash.vue
<template>
  <TresMesh
    :renderOrder="1"
    :scale="0.6"
    :frustumCulled="false"
    :position="[0, 0, 0.001]"
    :rotation="[0, 0, MathUtils.degToRad(45)]"
  >
    <TresPlaneGeometry />
    <TresMeshStandardMaterial
      transparent
      polygonOffset
      v-bind="maps"
      :depthWrite="false"
      :polygonOffsetFactor="-2"
      :blending="AdditiveBlending"
    />
  </TresMesh>
  <TresMesh
    :renderOrder="1"
    :scale="0.6"
    :frustumCulled="false"
    :position="[0, 0, 0.002]"
  >
    <TresPlaneGeometry />
    <TresMeshStandardMaterial
      transparent
      polygonOffset
      v-bind="maps"
      :depthWrite="false"
      :polygonOffsetFactor="-3"
      :blending="AdditiveBlending"
    />
  </TresMesh>
</template>

<script setup lang="ts">
import { useTexture } from "@tresjs/core";
import { AdditiveBlending, MathUtils } from "three";

const maps = await useTexture({
  map: "/decals/shmpulh_4K_Albedo.jpg",
  alphaMap: "/decals/shmpulh_4K_Opacity.jpg",
  normalMap: "/decals/shmpulh_4K_Normal.jpg",
  roughnessMap: "/decals/shmpulh_4K_Roughness.jpg",
  aoMap: "/decals/shmpulh_4K_AO.jpg"
});
</script>

// src/Floor/Trash.tsx
import { Circle, useTexture } from "@react-three/drei";
import { useLayoutEffect } from "react";
import { AdditiveBlending, MathUtils, RepeatWrapping } from "three";

export function Trash() {
  const maps = useTexture({
    map: "/demo-2023-rain-puddle/decals/trash/shmpulh_4K_Albedo.jpg",
    alphaMap: "/demo-2023-rain-puddle/decals/trash/shmpulh_4K_Opacity.jpg",
    normalMap: "/demo-2023-rain-puddle/decals/trash/shmpulh_4K_Normal.jpg",
    roughnessMap:
      "/demo-2023-rain-puddle/decals/trash/shmpulh_4K_Roughness.jpg",
    aoMap: "/demo-2023-rain-puddle/decals/trash/shmpulh_4K_AO.jpg",
  });

  useLayoutEffect(() => {
    for (const key in maps) {
      const map = maps[key];
      if (map) {
        map.wrapS = map.wrapT = RepeatWrapping;
        map.repeat.set(2, 2);
      }
    }
  }, []);

  return (
    <>
      <Circle
        args={[0.5]}
        renderOrder={1}
        frustumCulled={false}
        rotation-z={MathUtils.degToRad(30)}
        position={[0, 0, 0]}
      >
        <meshStandardMaterial
          {...maps}
          polygonOffset
          polygonOffsetFactor={-2}
          depthWrite={false}
          transparent
          blending={AdditiveBlending}
        />
      </Circle>
    </>
  );
}
